apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.88.0
    helm:
      releaseName: opentelemetry-operator  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opentelemetry-operator-system