apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demo
  namespace: argocd
spec:
  project: default
  source:
    chart: open-telemetry/opentelemetry-demo
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: main
    helm:
      releaseName: opentelemetry-demo  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: opentelemetry-demo