apiVersion: v1
kind: Service
metadata:
  labels:
    app: mario
  name: mario-deployment
  namespace: default
spec:
  clusterIP: 10.43.29.222
  clusterIPs:
  - 10.43.29.222
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mario
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}