apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.26.1
    helm:
      releaseName: vault
      parameters:
      - name: "server.insecure"
        value: "true"  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault