apiVersion: v1
data:
  applicationsetcontroller.enable.leader.election: "false"
  applicationsetcontroller.enable.progressive.syncs: "false"
  applicationsetcontroller.log.format: text
  applicationsetcontroller.log.level: info
  applicationsetcontroller.policy: sync
  controller.log.format: text
  controller.log.level: info
  controller.operation.processors: "10"
  controller.repo.server.timeout.seconds: "60"
  controller.self.heal.timeout.seconds: "5"
  controller.status.processors: "20"
  otlp.address: ""
  redis.server: my-argo-cd-argocd-redis:6379
  repo.server: my-argo-cd-argocd-repo-server:8081
  reposerver.log.format: text
  reposerver.log.level: info
  reposerver.parallelism.limit: "0"
  server.basehref: /
  server.dex.server: https://my-argo-cd-argocd-dex-server:5556
  server.dex.server.strict.tls: "false"
  server.disable.auth: "false"
  server.enable.gzip: "false"
  server.insecure: "true"
  server.log.format: text
  server.log.level: info
  server.repo.server.strict.tls: "false"
  server.rootpath: ""
  server.staticassets: /shared/app
  server.x.frame.options: sameorigin
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-argo-cd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2023-02-19T16:18:09Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: my-argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-5.22.0
  name: argocd-cmd-params-cm
  namespace: argocd
  resourceVersion: "527"
  uid: 519a6daa-32d8-49b2-9cd7-31d6f8ea5830
