apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: gitlab
spec:
  project: default
  source:
    chart: gitlab/gitlab
    repoURL: http://charts.gitlab.io/
    targetRevision: 7.5.1
    helm:
      releaseName: gitlab
      parameters:
      - name: "global.hosts.domain"
        value: "myk8s.net"  
      - name: "global.hosts.externalIP"
        value: "10.10.10.100"  
      - name: "certmanager-issuer.email"
        value: "me@example.com"
      - name: "postgresql.image.tag"
        value: "13.6.0"  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab