apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    path: cluster/
    repoURL: https://github.com/lobiplayer/myk8s_argocd.git
    targetRevision: HEAD
    directory:
        recurse: true
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
      automated:
        prune: true
        selfHeal: false