apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.22.1
    helm:
      releaseName: argo-cd
      parameters:
      - name: configs.params.server.insecure
        value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd