apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd

spec:
  rules:
    -  http:
        paths:
          - path: /argocd
            pathType: Exact
            backend:
              service:
                name: my-argo-cd-argocd-server
                port:
                  number: 80
          - path: /argocds
            pathType: Exact
            backend:
              service:
                name:  my-argo-cd-argocd-server
                port:
                  number: 443