apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/argoproj/argo-helm
    targetRevision: main
    helm:
      releaseName: argo-cd
      parameters:
      - name: "configs.params."server\.insecure""
        value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd