apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: vault-clusterissuer
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

spec:
  rules:
    - host: argocd.myk8s.net
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
  tls:
  - hosts:
    - argocd.myk8s.net
    secretName: argocd-secret # do not change, this is provided by Argo CD