apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://github.com/argoproj/argo-helm/tree/main/charts
    helm:
      releaseName: argo-cd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd