https://open-telemetry.github.io/opentelemetry-helm-charts
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: opentelemetry-helm
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.60.0
    helm:
      releaseName: opentelemetry-collector  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault