apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.22.1
    helm:
      releaseName: argo-cd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd