apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  cluserIssuerRef:
    name: vault-clusterissuer
  commonName: www.example.com
  dnsNames:
  - www.example.com