apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    argocd.argoproj.io/instance: root
  name: vault-issuer
  namespace: default
spec:
  vault:
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          key: token
          name: issuer-token-lmzpj
    caBundle: >
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMekNDQWhlZ0F3SUJBZ0lVTFlRaWZ4dUFh

      eFZLQno2WXVyMnRXRHF2SS80d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF4TUpi

      WGxyT0hNdWJtVjBNQjRYRFRJek1EUXdNVEUzTWpFMU9Gb1hEVEkwTURNegpNVEUzTWpJeU4xb3dG

      REVTTUJBR0ExVUVBeE1KYlhsck9ITXVibVYwTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NB

      UThBTUlJQkNnS0NBUUVBNllPVzN3YXRMV0lDTGFLYlhudWJwMTVEYWFSRkFqQ2oxZVpRQWNYMUZM

      aFIKM1JEcGlNNEM1Vmh2bFpWc2ZIVzBMVzV4U25nMXNvMFhxazMyOWtDWTk2Yy9xK3BmYS9ySi9u

      Q3JFVVFGdFYvdwplYTV3SUpiT2YrL0gzY1ovYTNPSzNuV3RWUGE1RUJqSVBEakNNMUhtR3M0cU5u

      U3dQZzVlc2pGbjVJaGwyV0FPCnZQZDNlMXlidlkxVlczVnY3WGlIam90NkNmREdqS2FwSVBXcGlp

      R294bHl1T0lqa0Nwcyt5cElRRjlIbzhrR0wKaGRtak9LT280TWdxZjlhSWV0a3JBTy9nZnJWVGhs

      ZXNuc0l2Y0ptcTNtYkdGWEo1bTZiRzkxWFVFeUkzZTMrTgprT095QURTLy82K2dsZUpkRm1vazI2

      c0ZTc2tKaEhiK3lRUENCYzIyS1FJREFRQUJvM2t3ZHpBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3

      WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUkvTnpKTUpneUI4c1dDbVMKZjEyZFV3

      WVlrbHN3SHdZRFZSMGpCQmd3Rm9BVUkvTnpKTUpneUI4c1dDbVNmMTJkVXdZWWtsc3dGQVlEVlIw

      UgpCQTB3QzRJSmJYbHJPSE11Ym1WME1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2F3NlpzaWVM

      RnRhNk9jdFVaCjBFNHhyaCtWK2Z3a1J6TlpOZUs1UXZVMW05WU1sNFhlTXJvYjY4c1pwd0NBZ3hH

      N0wyVU1oNkxHVnJ1ZzFGSDQKVmlWbXJaQ1V2V1VZMW1ITlQ0MjV1OGlRZ0VBbHVhSFNPbUM5KzFt

      U0JDNUl6TStGbjRGVVdTb3JlYjdGOXMzbAp4b3FtNzBhZWlUS3ltMks2SGpudjJGVzRWVjExaFVj

      UjVDTVBIKzRXR3RMOXZyZ0lwU2RWV004V3VLRmhHSjA2Ckp0SXBVNi80YTlBSUY3bjY0YjUwUnJP

      ZXowRnJtTTN4ZzdjNGFYY0RSWXBKQjhCZHNDSGxYSmZid041YWRTbUUKOUlRdjFZRFZPYTEyT1BF

      MTlkSlV6V1F4YVVVa09mUFFENDNQLy9ia2ZsY0g2dEh3KzdBbWQrMGx5NjNzV2RTSwpDMHV3Ci0t

      LS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    path: pki/sign/myk8s-dot-net
    server: 'http://10.10.10.201:8200'
