apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: default
spec:
  vault:
    server: http://10.10.10.201
    path: pki/sign/myk8s-dot-net
    caBundle: |
      MIIDLzCCAhegAwIBAgIULYQifxuAaxVKBz6Yur2tWDqvI/4wDQYJKoZIhvcNAQEL
      BQAwFDESMBAGA1UEAxMJbXlrOHMubmV0MB4XDTIzMDQwMTE3MjE1OFoXDTI0MDMz
      MTE3MjIyN1owFDESMBAGA1UEAxMJbXlrOHMubmV0MIIBIjANBgkqhkiG9w0BAQEF
      AAOCAQ8AMIIBCgKCAQEA6YOW3watLWICLaKbXnubp15DaaRFAjCj1eZQAcX1FLhR
      3RDpiM4C5VhvlZVsfHW0LW5xSng1so0Xqk329kCY96c/q+pfa/rJ/nCrEUQFtV/w
      ea5wIJbOf+/H3cZ/a3OK3nWtVPa5EBjIPDjCM1HmGs4qNnSwPg5esjFn5Ihl2WAO
      vPd3e1ybvY1VW3Vv7XiHjot6CfDGjKapIPWpiiGoxlyuOIjkCps+ypIQF9Ho8kGL
      hdmjOKOo4Mgqf9aIetkrAO/gfrVThlesnsIvcJmq3mbGFXJ5m6bG91XUEyI3e3+N
      kOOyADS//6+gleJdFmok26sFSskJhHb+yQPCBc22KQIDAQABo3kwdzAOBgNVHQ8B
      Af8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUI/NzJMJgyB8sWCmS
      f12dUwYYklswHwYDVR0jBBgwFoAUI/NzJMJgyB8sWCmSf12dUwYYklswFAYDVR0R
      BA0wC4IJbXlrOHMubmV0MA0GCSqGSIb3DQEBCwUAA4IBAQCaw6ZsieLFta6OctUZ
      0E4xrh+V+fwkRzNZNeK5QvU1m9YMl4XeMrob68sZpwCAgxG7L2UMh6LGVrug1FH4
      ViVmrZCUvWUY1mHNT425u8iQgEAluaHSOmC9+1mSBC5IzM+Fn4FUWSoreb7F9s3l
      xoqm70aeiTKym2K6Hjnv2FW4VV11hUcR5CMPH+4WGtL9vrgIpSdVWM8WuKFhGJ06
      JtIpU6/4a9AIF7n64b50RrOez0FrmM3xg7c4aXcDRYpJB8BdsCHlXJfbwN5adSmE
      9IQv1YDVOa12OPE19dJUzWQxaUUkOfPQD43P//bkflcH6tHw+7Amd+0ly63sWdSK
      C0uw
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: issuer-token-lmzpj
          key: token