apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mario
  namespace: default
  labels:
spec:
  rules:
  - host: myk8s.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myservicea
            port:
              number: 80
  ingressClassName: nginx