apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myk8s.net
  namespace: default
spec:
  secretName: myk8s.net-tls
ClusterIssuerRef:
    name: vault-clusterissuer
  commonName: myk8s.net
  dnsNames:
  - myk8s.net
