apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-myk8s-dot-net
  namespace: default
spec:
  secretName: myk8s.net-tls
  issuerRef:
      name: vault-clusterissuer
      kind: ClusterIssuer
  commonName: test.myk8s.net
  dnsNames:
  - test.myk8s.net
