apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-clusterissuer
  namespace: cert-manager
spec:
  vault:
    server: http://vault.vault
    path: pki/sign/example-dot-com
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: issuer
        secretRef:
          name: clusterissuer-token-lmzpj
          key: token