
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mario-ingress
  annotations:
    # ingress.kubernetes.io/rewrite-target: /mario
spec:
  rules:
  - http:
      paths:
        - path: /mario
          backend:
            serviceName: mario-deployement
            servicePort: 8080