apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-09T15:59:52Z"
  labels:
    app: mario
    argocd.argoproj.io/instance: root
  name: mario-deployment
  namespace: default
  resourceVersion: "187801"
  uid: c64cfa65-f353-4258-b24c-4564eb6d77ad
spec:
  clusterIP: 10.43.29.222
  clusterIPs:
  - 10.43.29.222
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mario
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}