apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mario
  namespace: default
  labels:
spec:
  rules:
  - host: mario.myk8s.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: mario-deployment
            port:
              number: 8080