apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-mario
spec:
  ingressClassName: nginx
  rules:
  - host: myk8s.net
    http:
      paths:
      - path: /mario
        backend:
          serviceName: mario-deployement
          servicePort: 8080