apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: default
  source:
    path: traefik
    repoURL: https://github.com/traefik/traefik-helm-chart
    targetRevision: master
    helm:
      releaseName: traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik